### PR TITLE
simplify for travis

### PR DESCRIPTION
**Pull request by remicollet**
*    don't install build extension
*    fix PHP_TEST_ARGS
*    don't use any ini file, rely on PHP defaults + explicit args

### CODE REVIEW

**Comment by remicollet** [comment]
Differred as I have issue to access travis log... :(

BTW @derickr  just tell me if this change have some value ?

**Comment by derickr** [comment]
This seems reasonable. It is still WIP?

**Comment by remicollet** [comment]
> It is still WIP?

I want to check if opcache really disabled... but can't read travis log....
So yes, WIP until I can check :(

**Comment by remicollet** [comment]
PR squashed, everything seems OK.

With USE_OPCACHE=0

```
$ $MYPHP $TEST_PHP_ARGS -v
PHP 7.2.0RC6 (cli) (built: Nov 14 2017 03:20:47) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0-dev, Copyright (c) 2002-2017, by Derick Rethans
```

With USE_OPCACHE=1

```
$ $MYPHP $TEST_PHP_ARGS -v
PHP 7.0.22 (cli) (built: Aug 17 2017 15:55:02) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0-dev, Copyright (c) 2002-2017, by Derick Rethans
```

So, ready for review :)

**Comment by remicollet** [comment]
also:
* drop MYPHP use TEST_PHP_EXECUTABLE evreywhere
* drop xdebug.auto_trace=0 which is the builtin default (and php.ini not used, so we can rely on Xdebug default)

**Comment by derickr** [comment]
Merged, after rebase and squash.

**Comment by derickr** [comment]
Thanks again Remi!

**Pull request closed without merging**
