### PR TITLE
Reset overloaded opcodes at the end of each request

### PR DESCRIPTION
**Pull request by kaplanlior**
An improved fix over c50a75d8

### CODE REVIEW

**Comment by kaplanlior** [comment]
Update branch instead of #184

**Comment by derickr** [comment]
Sorry, but with this change, *all* the Travis tests turn into segfaults: https://travis-ci.org/xdebug/xdebug/jobs/66759016

**Comment by kaplanlior** [comment]
I saw, we'll check what went wrong tomorrow. I'll mail you when all the travis checks are fine.

**Comment by kaplanlior** [comment]
Fixed code to also run in ZTS mode.

**Pull request merged**
