### PR TITLE
Fixed issue #1948: Don't send messages to PHP's error log if Xdebug log is active

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by adam1010** [comment]
@derickr  Will this improvement will be in `3.0.5` release?  Right now when I run my unit tests I get spammed really bad, and my understanding is that by setting `xdebug.log` this will all go away?

image

**Comment by derickr** [comment]
It will be in 3.1.0, which will be the next release — currently planning for the end of June.

There won't be a 3.0.5 unless there is a critical (crash) bug.

**Comment by suikoy** [comment]
@derickr Hi is there any news about the release date for 3.1.0? Thanks

**Comment by derickr** [comment]
On Sun, 1 Aug 2021, suikoy wrote:

> @derickr Hi is there any news about the release date for 3.1.0? Thanks

Not yet, I'm still ironing out a few issues:
https://bugs.xdebug.org/roadmap_page.php?version_id=87

cheers,
Derick

**Comment by Levdbas** [comment]
Hi, I'm looking forward for the 3.1.0 release since all these messages get written to my error.log file as well. Is there a workaround to stop this from happening for now?

**Pull request merged**
