### PR TITLE
Fixed issue #1665: Segfault when overriding a function object parameter

### PR DESCRIPTION
**Pull request by SpyroTEQ**
XDebug might need to dump stack traces and such,
so we must hold a reference to the PHP variables
Otherwise, PHP might garbage collect these variables,
and XDebug will segfault when trying to dump them

Note that I've based this on the xdebug_2_7 branch, which conflicts with master, so I'm opening pull request on the xdebug_2_7 branch too. The "contributing" page is not clear about that IMO. if needed, I can merge with master (merge is fairly easy, the only conflict is about 2 clocks of added lines so just add both)

Note again: I've merged with the master because I'm used to do so and I didn't think twice, but I'm not 100% it was a right thing to do?! Tell me if you want me to "undo" the merge and I'll refork the 2.7 branch, recommit, and not merge with master

### CODE REVIEW

**Comment by derickr** [comment]
This PR looks like it has the `master` branch merged in. Can you perhaps make a clean feature branch of `xdebug_2_7` with only your own commits cherry picked in it?

**Comment by derickr** [comment]
Sorry, I just saw that you actually asked about that. So yes, please refork and re-apply your commits. It's not a usual case, and GitHub is a bit silly here, which is why I hadn't put it in the contributing guidelines.

Also, I'd like to say thanks for looking into this. It's been on my list for a while, and I'm looking forwards to the clean PR so that I can review it.

cheers,
Derick

**Comment by SpyroTEQ** [comment]
Alright, I'm gonna do so then. You're welcome tho, I feel proud and happy to have contributed for an open source PHP related project for the first time (and for a pretty challenging bug tho!) :)

**Comment by SpyroTEQ** [comment]
PR reopened here https://github.com/xdebug/xdebug/pull/474 I'll close this one

**Pull request closed without merging**
