### PR TITLE
Issue 1752 - Use a vector instead of a linked list to manage the stack

### PR DESCRIPTION
**Pull request by carlos-granados**
The current implementation of the stack uses a linked list of stack entries. This is inefficient because we are allocating and freeing memory every time that we enter or leave a function. This can be implemented in a more efficient way using a vector (an array of objects whose size can grow dynamically at run time)

I implemented this using the code found here for implementing a vector in C as a basis:

https://github.com/eteran/c-vector

I modified the code a little bit to add some extra functionality, adapt it to our needs and adapt it to the XDEBUG terminology

I have benchmarked this by running this PHP function (Calculates the Fibonacci number using a recursive algorithm):

```
<?php
function fib($n) {
    if ($n <= 1) { return 1; }
    return fib($n - 1) + fib($n - 2);
}

echo fib(35);
?>
```
with XDebug enabled, connected to a debug client, no code coverage, profiling or tracing. With the current master, the average run time (taken over 10 runs) is 2m15s. With my branch the average run time is 2m08s. So, not a big improvement (5%), specially taking into account that this code probably overstates the importance of function calls in php code, but points in the good direction as I believe we may be able to do something similar for many other data used by XDebug

### CODE REVIEW

**Comment by carlos-granados** [comment]
I can see some errors thrown by the compiler when running the tests, not sure why these errors are not thrown when compiling locally, I will add some fixes for this

**Comment by derickr** [comment]
CI runs with `--enable-xdebug-dev`. Please use that locally too.

**Comment by mvorisek** [comment]
@carlos-granados do you plan to finish this?

**Comment by derickr** [comment]
On 19 July 2020 10:23:21 BST, "Michael Voříšek" <notifications@github.com> wrote:
>@carlos-granados do you plan to finish this?

I'm going to take this idea and implement it on twitch stream tomorrow. And explain why this is a better approach.

**Comment by derickr** [comment]
I'm closing this as I've merged a similar implementation through #609. Thanks for the idea!

**Comment by carlos-granados** [comment]
Glad that it helped!

**Pull request closed without merging**
