### PR TITLE
Add GitHub Actions configuration

### PR DESCRIPTION
**Pull request by jakzal**
This aims to be the same build as Travis CI configuration currently provides. PHP 8.1 is additionally provided.

Some ideas for future improvements:
* the extension could be published as a build artifact
* builds could be run on other platforms (windows, macos)
* ~`.travis.scripts` could be renamed to `.build.scripts`, or moved to `.github/scripts` once Travis is dropped~ done

image

### CODE REVIEW

**Comment by jakzal** [comment]
One test seems to be occasionally failing:

```==========================================================================
14 tests/base/bug01266.diff
15 --------------------------------------------------------------------------
16 001+ Notice: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) in /home/runner/work/xdebug/xdebug/tests/base/bug01266.php on line 2
17 002+ 
18 003+ Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/runner/work/xdebug/xdebug/tests/base/bug01266.php:2) in /home/runner/work/xdebug/xdebug/tests/base/bug01266.php on line 2
19 004+ ==========================================================================```

I'm not sure if it's GitHub, or is it a known issue.

**Comment by jakzal** [comment]
I changed the session.save_path to /tmp.

**Comment by jakzal** [comment]
Travis CI config now removed.

**Review by derickr — CHANGES_REQUESTED** [review]
If you'd please squash the first (add GH) and second (change save_path) commits (but leave the third on its own), then this looks ready to merge.

Thanks!

**Pull request merged**
