### PR TITLE
Fixed issue #2221: Crash when other extensions run PHP code without the stack being initialised yet

### PR DESCRIPTION
**Pull request by derickr**
Take three. Replaces #936 and #938.

### CODE REVIEW

**Comment by lcobucci** [comment]
I've reduced the test scope and can still reproduce the `SIGSEGV` when using `dd-trace` and Xdebug 3.3.

<details>
<summary>Dockerfile</summary>

```Dockerfile
FROM php:8.3-alpine3.18

RUN apk add --no-cache gdb \
    && apk add --no-cache --virtual .build-deps ${PHPIZE_DEPS} linux-headers \
    && docker-php-ext-install -j$(nproc) sockets \
    && curl -LOs https://github.com/DataDog/dd-trace-php/releases/download/0.95.0/datadog-setup.php  \
    && php datadog-setup.php --php-bin=all --enable-profiling  \
    && rm datadog-setup.php \
    && mkdir -p /tmp/xdebug \
    && wget https://github.com/derickr/xdebug/archive/refs/heads/issue2221-take3.zip -O /tmp/xdebug/patch.zip \
    && cd /tmp/xdebug \
    && unzip patch.zip \
    && cd xdebug-issue2221-take3 \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && docker-php-ext-enable xdebug \
    && rm -rf /tmp/xdebug \
    && apk del .build-deps

ENV DD_TRACE_CLI_ENABLED=1

RUN echo "<?php throw new Exception('Nope'); " > /var/www/html/test.php

CMD ["php", "test.php"]
```
</details>

<details>
<summary>gdb full bt</summary>

```gdb
# gdb php
GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...
(No debugging symbols found in php)
(gdb) run test.php
Starting program: /usr/local/bin/php test.php
warning: Error disabling address space randomization: Operation not permitted
[Detaching after fork from child process 28]
[New LWP 30]
[New LWP 31]
[New LWP 32]

Thread 1 "php" received signal SIGSEGV, Segmentation fault.
zval_from_stack (output=output@entry=0x7fe9e73d2488 <xdebug_globals+1064>, add_local_vars=add_local_vars@entry=true, params_as_values=params_as_values@entry=true)
    at /tmp/xdebug/xdebug-issue2221-take3/src/develop/stack.c:489
489	/tmp/xdebug/xdebug-issue2221-take3/src/develop/stack.c: No such file or directory.
(gdb) bt full
#0  zval_from_stack (output=output@entry=0x7fe9e73d2488 <xdebug_globals+1064>, add_local_vars=add_local_vars@entry=true, params_as_values=params_as_values@entry=true)
    at /tmp/xdebug/xdebug-issue2221-take3/src/develop/stack.c:489
        fse = 0x0
        next_fse = 0xf0
        i = 0
#1  0x00007fe9e73b1d17 in xdebug_develop_throw_exception_hook (exception=exception@entry=0x7fe9e5d551e0, file=file@entry=0x7fe9e5d55238, line=line@entry=0x7fe9e5d55248, 
    code=code@entry=0x7fe9e5d55228, code_str=code_str@entry=0x0, message=message@entry=0x7fe9e5d55208) at /tmp/xdebug/xdebug-issue2221-take3/src/develop/stack.c:1244
        exception_ce = 0x7fe9e765c510
        exception_trace = <optimized out>
        tmp_str = {l = 127, a = 1025, 
          d = 0x7fe9e66c04d0 "\nException: Nope in /var/www/html/test.php on line 1\n\nCall Stack:\n    0.0127    3127840   1. {main}() /var/www/html/test.php:0\n"}
        z_previous_exception = <optimized out>
        z_last_exception_slot = <optimized out>
        z_previous_trace = <optimized out>
        previous_exception_obj = <optimized out>
        dummy = {value = {lval = 140642586314000, dval = 6.9486670240009672e-310, counted = 0x7fe9e765c510, str = 0x7fe9e765c510, arr = 0x7fe9e765c510, 
            obj = 0x7fe9e765c510, res = 0x7fe9e765c510, ref = 0x7fe9e765c510, ast = 0x7fe9e765c510, zv = 0x7fe9e765c510, ptr = 0x7fe9e765c510, ce = 0x7fe9e765c510, 
            func = 0x7fe9e765c510, ww = {w1 = 3882206480, w2 = 32745}}, u1 = {type_info = 3855962592, v = {type = 224 '\340', type_flags = 81 'Q', u = {
                extra = 58837}}}, u2 = {next = 32745, cache_slot = 32745, opline_num = 32745, lineno = 32745, num_args = 32745, fe_pos = 32745, fe_iter_idx = 32745, 
            guard = 32745, constant_flags = 32745, extra = 32745}}
#2  0x00007fe9e7389057 in xdebug_throw_exception_hook (exception=0x7fe9e5d551e0) at /tmp/xdebug/xdebug-issue2221-take3/src/base/base.c:1575
        code = 0x7fe9e5d55228
        message = 0x7fe9e5d55208
        file = 0x7fe9e5d55238
        line = 0x7fe9e5d55248
        exception_ce = <optimized out>
        code_str = 0x0
        dummy = {value = {lval = 22, dval = 1.0869444208507424e-322, counted = 0x16, str = 0x16, arr = 0x16, obj = 0x16, res = 0x16, ref = 0x16, ast = 0x16, zv = 0x16, 
            ptr = 0x16, ce = 0x16, func = 0x16, ww = {w1 = 22, w2 = 0}}, u1 = {type_info = 3865884448, v = {type = 32 ' ', type_flags = 183 '\267', u = {
                extra = 58988}}}, u2 = {next = 32745, cache_slot = 32745, opline_num = 32745, lineno = 32745, num_args = 32745, fe_pos = 32745, fe_iter_idx = 32745, 
            guard = 32745, constant_flags = 32745, extra = 32745}}
#3  xdebug_throw_exception_hook (exception=0x7fe9e5d551e0) at /tmp/xdebug/xdebug-issue2221-take3/src/base/base.c:1527
        code = <optimized out>
        message = <optimized out>
        file = <optimized out>
        line = <optimized out>
        exception_ce = <optimized out>
        code_str = <optimized out>
        dummy = <optimized out>
#4  0x000055b2d1a3eaf5 in zend_throw_exception_internal ()
No symbol table info available.
#5  0x00007fe9e6e85a88 in zim_DDTrace_ExceptionOrErrorHandler_execute (execute_data=0x7fe9e7414020, return_value=0x7ffd869c7d50)
    at /home/circleci/datadog/tmp/build_extension/ext/handlers_exception.c:308
        __orig_bailout = 0x7ffd869c8f40
        __bailout = {{__jb = {140642584300104, 1, 0, 140726861855968, 94226528463296, 0, 140726861854960, 140642578443283}, __fl = 140726861855752, __ss = {
              140726861855648, 140726861855768, 140642586313312, 140642568163888, 4485274959436054656, 140642560070200, 140642560070216, 140642560070152, 
              4485274959436054656, 140642586314000, 0, 0, 140726861855968, 94226528463296, 0, 140726861855976}}}
        root_span = 0x7fe9e74be000
        exception = 0x7fe9e5d551e0
        span_exception = 0x7fe9e74be0d8
        old_exception = {value = {lval = 4607182418800017408, dval = 1, counted = 0x3ff0000000000000, str = 0x3ff0000000000000, arr = 0x3ff0000000000000, 
            obj = 0x3ff0000000000000, res = 0x3ff0000000000000, ref = 0x3ff0000000000000, ast = 0x3ff0000000000000, zv = 0x3ff0000000000000, ptr = 0x3ff0000000000000, 
            ce = 0x3ff0000000000000, func = 0x3ff0000000000000, ww = {w1 = 0, w2 = 1072693248}}, u1 = {type_info = 1, v = {type = 1 '\001', type_flags = 0 '\000', u = {
                extra = 0}}}, u2 = {next = 0, cache_slot = 0, opline_num = 0, lineno = 0, num_args = 0, fe_pos = 0, fe_iter_idx = 0, guard = 0, constant_flags = 0, 
            extra = 0}}
        has_bailout = false
        is_error_handler = <optimized out>
        handler = 0x7fe9e7470a70
#6  0x00007fe9e69bc6b5 in datadog_php_profiling::execute_internal () at profiling/src/lib.rs:1104
No locals.
#7  0x000055b2d1d5e1f6 in zend_call_function ()
No symbol table info available.
#8  0x000055b2d1d5e3b8 in _call_user_function_impl ()
No symbol table info available.
#9  0x000055b2d1a2a6a8 in zend_user_exception_handler ()
No symbol table info available.
#10 0x000055b2d1a2a738 in ?? ()
No symbol table info available.
#11 0x000055b2d1d01ef0 in php_execute_script ()
No symbol table info available.
#12 0x000055b2d1e56938 in ?? ()
No symbol table info available.
#13 0x000055b2d1a483a1 in ?? ()
No symbol table info available.
#14 0x00007fe9e8296aad in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#15 0x00007fe9e8296a85 in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#16 0x00007ffd869cb5d0 in ?? ()
No symbol table info available.
#17 0x0000000000000000 in ?? ()
No symbol table info available.
```
</details>

I hope that helps :+1:

**Comment by edsrzf** [comment]
Thanks @lcobucci, I see the same thing. I previously commented on the issue tracker that my crash with dd-trace was resolved, but I realized yesterday I made a mistake when testing and was not actually testing against XDebug 3.3.0 (let alone with the fix).

**Comment by derickr** [comment]
@lcobucci I think you found a different issue than what I fixed (in #942) — your stack trace shows something to do with an exception. I'll have a look.

**Comment by lcobucci** [comment]
Thanks @derickr!

**Comment by derickr** [comment]
@lcobucci it'd be great if you could test that branch with your own code, before I merge it.

**Comment by lcobucci** [comment]
> @lcobucci it'd be great if you could test that branch with your own code, before I merge it.

@derickr sorry that I couldn't test before the merge. The patch did solve the issue I posted here, however I'm still having `SIGSEGV` against my code :cry: 

```
PHP 8.2.13 (cli) (built: Dec 12 2023 22:22:03) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.13, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1-dev, Copyright (c) 2002-2023, by Derick Rethans
    with ddtrace v0.95.0, Copyright Datadog, by Datadog
    with datadog-profiling v0.95.0, Copyright Datadog, by Datadog
    with ddappsec v0.95.0, Copyright Datadog, by Datadog
```

<details>
<summary>php -m</summary>

```sh
# php -m
[PHP Modules]
bcmath
Core
ctype
curl
datadog-profiling
date
ddappsec
ddtrace
dom
fileinfo
filter
ftp
grpc
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
random
readline
Reflection
session
SimpleXML
sockets
sodium
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
datadog-profiling
ddappsec
ddtrace
```
</details>

<details>
<summary>gdb bt full</summary>

```gdb
Thread 1 "php" received signal SIGSEGV, Segmentation fault.
0x00007fe518a336c9 in zval_from_stack_add_frame_variables (opa=0x7fe51608c5b8, symbols=<optimized out>, edata=0x7fe518c14120, frame=0x7fe51592ffe0)
    at /tmp/xdebug-xdebug_3_3/src/develop/stack.c:431
431			symbol_name = xdebug_str_create_from_char(opa->vars[j]->val);
(gdb) bt full
#0  0x00007fe518a336c9 in zval_from_stack_add_frame_variables (opa=0x7fe51608c5b8, symbols=<optimized out>, edata=0x7fe518c14120, frame=0x7fe51592ffe0)
    at /tmp/xdebug-xdebug_3_3/src/develop/stack.c:431
        symbol_name = <optimized out>
        symbol = {value = {lval = 140621887145672, dval = 6.9476443492041322e-310, counted = 0x7fe515a186c8, str = 0x7fe515a186c8, arr = 0x7fe515a186c8, 
            obj = 0x7fe515a186c8, res = 0x7fe515a186c8, ref = 0x7fe515a186c8, ast = 0x7fe515a186c8, zv = 0x7fe515a186c8, ptr = 0x7fe515a186c8, ce = 0x7fe515a186c8, 
            func = 0x7fe515a186c8, ww = {w1 = 362907336, w2 = 32741}}, u1 = {type_info = 775, v = {type = 7 '\a', type_flags = 3 '\003', u = {extra = 0}}}, u2 = {
            next = 0, cache_slot = 0, opline_num = 0, lineno = 0, num_args = 0, fe_pos = 0, fe_iter_idx = 0, property_guard = 0, constant_flags = 0, extra = 0}}
        j = 0
        variables = {value = {lval = 140621880999144, dval = 6.9476440455252996e-310, counted = 0x7fe51543bce8, str = 0x7fe51543bce8, arr = 0x7fe51543bce8, 
            obj = 0x7fe51543bce8, res = 0x7fe51543bce8, ref = 0x7fe51543bce8, ast = 0x7fe51543bce8, zv = 0x7fe51543bce8, ptr = 0x7fe51543bce8, ce = 0x7fe51543bce8, 
            func = 0x7fe51543bce8, ww = {w1 = 356760808, w2 = 32741}}, u1 = {type_info = 775, v = {type = 7 '\a', type_flags = 3 '\003', u = {extra = 0}}}, u2 = {
            next = 22009, cache_slot = 22009, opline_num = 22009, lineno = 22009, num_args = 22009, fe_pos = 22009, fe_iter_idx = 22009, property_guard = 22009, 
            constant_flags = 22009, extra = 22009}}
#1  zval_from_stack_add_frame (output=0x7fe518a56478 <xdebug_globals+1048>, fse=0x7fe516b71250, edata=0x7fe518c14120, add_local_vars=<optimized out>, 
    params_as_values=<optimized out>) at /tmp/xdebug-xdebug_3_3/src/develop/stack.c:467
        frame = <optimized out>
#2  0x00007fe518a33b2f in zval_from_stack (output=output@entry=0x7fe518a56478 <xdebug_globals+1048>, add_local_vars=add_local_vars@entry=true, 
    params_as_values=params_as_values@entry=true) at /tmp/xdebug-xdebug_3_3/src/develop/stack.c:495
        fse = 0x7fe516b71250
        next_fse = 0x7fe516b71340
        i = 2
#3  0x00007fe518a35ef7 in xdebug_develop_throw_exception_hook (exception=exception@entry=0x7fe5154235a0, file=file@entry=0x7fe5154235f8, line=line@entry=0x7fe515423608, 
    code=code@entry=0x7fe5154235e8, code_str=code_str@entry=0x0, message=message@entry=0x7fe5154235c8) at /tmp/xdebug-xdebug_3_3/src/develop/stack.c:1252
        exception_ce = 0x7fe515918390
        exception_trace = <optimized out>
        tmp_str = {l = 41767, a = 42196, 
          d = 0x7fe5157f4fe0 "\nSymfony\\Component\\DependencyInjection\\Exception\\EnvNotFoundException: Environment variable not found: \"APP_RUNTIME_ENV\". in /var/www/vendor/symfony/dependency-injection/EnvVarProcessor.php on line 20"...}
        z_previous_exception = <optimized out>
        z_last_exception_slot = <optimized out>
        z_previous_trace = <optimized out>
        previous_exception_obj = <optimized out>
        dummy = {value = {lval = 140621886096272, dval = 6.9476442973568833e-310, counted = 0x7fe515918390, str = 0x7fe515918390, arr = 0x7fe515918390, 
            obj = 0x7fe515918390, res = 0x7fe515918390, ref = 0x7fe515918390, ast = 0x7fe515918390, zv = 0x7fe515918390, ptr = 0x7fe515918390, ce = 0x7fe515918390, 
            func = 0x7fe515918390, ww = {w1 = 361857936, w2 = 32741}}, u1 = {type_info = 356660640, v = {type = 160 '\240', type_flags = 53 '5', u = {extra = 5442}}}, 
          u2 = {next = 32741, cache_slot = 32741, opline_num = 32741, lineno = 32741, num_args = 32741, fe_pos = 32741, fe_iter_idx = 32741, property_guard = 32741, 
            constant_flags = 32741, extra = 32741}}
#4  0x00007fe518a0d0a7 in xdebug_throw_exception_hook (exception=0x7fe5154235a0) at /tmp/xdebug-xdebug_3_3/src/base/base.c:1580
        code = 0x7fe5154235e8
        message = 0x7fe5154235c8
        file = 0x7fe5154235f8
        line = 0x7fe515423608
        exception_ce = <optimized out>
        code_str = 0x0
        dummy = {value = {lval = 140621940027448, dval = 6.9476469619110135e-310, counted = 0x7fe518c87038, str = 0x7fe518c87038, arr = 0x7fe518c87038, 
            obj = 0x7fe518c87038, res = 0x7fe518c87038, ref = 0x7fe518c87038, ast = 0x7fe518c87038, zv = 0x7fe518c87038, ptr = 0x7fe518c87038, ce = 0x7fe518c87038, 
            func = 0x7fe518c87038, ww = {w1 = 415789112, w2 = 32741}}, u1 = {type_info = 652169182, v = {type = 222 '\336', type_flags = 79 'O', u = {extra = 9951}}}, 
          u2 = {next = 22009, cache_slot = 22009, opline_num = 22009, lineno = 22009, num_args = 22009, fe_pos = 22009, fe_iter_idx = 22009, property_guard = 22009, 
            constant_flags = 22009, extra = 22009}}
#5  xdebug_throw_exception_hook (exception=0x7fe5154235a0) at /tmp/xdebug-xdebug_3_3/src/base/base.c:1532
        code = <optimized out>
        message = <optimized out>
        file = <optimized out>
        line = <optimized out>
        exception_ce = <optimized out>
        code_str = <optimized out>
        dummy = <optimized out>
#6  0x000055f926a3d0ca in zend_throw_exception_internal ()
No symbol table info available.
#7  0x000055f926a3518e in ?? ()
No symbol table info available.
#8  0x000055f926dc2c0d in execute_ex ()
No symbol table info available.
#9  0x000055f926a3b0ef in ?? ()
No symbol table info available.
#10 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#11 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#12 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#13 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#14 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#15 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#16 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#17 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#18 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#19 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#20 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#21 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#22 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#23 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#24 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#25 0x000055f926de1fa2 in zend_generator_resume ()
No symbol table info available.
#26 0x000055f926de2bd9 in ?? ()
No symbol table info available.
#27 0x000055f926d7d166 in ?? ()
No symbol table info available.
#28 0x000055f926d8f273 in ?? ()
No symbol table info available.
#29 0x000055f926dc3a4f in execute_ex ()
No symbol table info available.
#30 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#31 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#32 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#33 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#34 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#35 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#36 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#37 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#38 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#39 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#40 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#41 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#42 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#43 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#44 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#45 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#46 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#47 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#48 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#49 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#50 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#51 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#52 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#53 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#54 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#55 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#56 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#57 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#58 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#59 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#60 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#61 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#62 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#63 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#64 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#65 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#66 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#67 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#68 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#69 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#70 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#71 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#72 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#73 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#74 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#75 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#76 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#77 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#78 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#79 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#80 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#81 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#82 0x000055f926a3b0ef in ?? ()
No symbol table info available.
#83 0x000055f926a3bb34 in ?? ()
No symbol table info available.
#84 0x000055f926d9c86c in ?? ()
No symbol table info available.
#85 0x000055f926dc2635 in execute_ex ()
No symbol table info available.
#86 0x000055f926dcb873 in zend_execute ()
No symbol table info available.
#87 0x000055f926d5bd98 in zend_execute_scripts ()
No symbol table info available.
#88 0x000055f926cf6d70 in php_execute_script ()
No symbol table info available.
#89 0x000055f926e4089a in ?? ()
No symbol table info available.
#90 0x000055f926a46681 in ?? ()
No symbol table info available.
#91 0x00007fe519a45aad in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#92 0x00007fe519a45a85 in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#93 0x00007ffc6947f180 in ?? ()
No symbol table info available.
#94 0x0000000000000000 in ?? ()
No symbol table info available.
```
</details>

**Comment by derickr** [comment]
@lcobucci I hadn't realised that it hadn't fixed this issue. Can you open a new one at https://bugs.php.net, with a full set of reproducible steps? Preferably *not* in Docker, as that makes it a PITA to debug.

**Comment by lcobucci** [comment]
> @lcobucci I hadn't realised that it hadn't fixed this issue. Can you open a new one at https://bugs.php.net, with a full set of reproducible steps? Preferably *not* in Docker, as that makes it a PITA to debug.

@derickr it has been resolved later on.

I believe it required changes on dd-trace too, which they have addressed.

**Comment by magyargergo** [comment]
Hey @derickr,

I have seen XDebug v3.3.1 has a [fix for empty stack](https://bugs.xdebug.org/view.php?id=2221)  but I've got segmentation fault when running unit tests. I've included the staktrace of the error.

```
0x00007f82fe06e7d7 in zval_from_stack_add_frame_variables (opa=0x7f82d2bcc000, opa=0x7f82d2bcc000, symbols=<optimized out>, edata=0x7f82fe61a0b0, frame=0x7f82d2f3fd00)
    at /home/dev/xdebug/src/develop/stack.c:431
431	/home/dev/xdebug/src/develop/stack.c: No such file or directory.
#0  0x00007f82fe06e7d7 in zval_from_stack_add_frame_variables (opa=0x7f82d2bcc000, opa=0x7f82d2bcc000, symbols=<optimized out>, edata=0x7f82fe61a0b0, frame=0x7f82d2f3fd00)
    at /home/dev/xdebug/src/develop/stack.c:431
#1  zval_from_stack_add_frame (output=output@entry=0x7f82fe28f4d0 <xdebug_globals+1072>, fse=fse@entry=0x555c5e828f40, edata=0x7f82fe61a0b0,
    add_local_vars=add_local_vars@entry=true, params_as_values=params_as_values@entry=true) at /home/dev/xdebug/src/develop/stack.c:467
#2  0x00007f82fe06eaff in zval_from_stack (output=output@entry=0x7f82fe28f4d0 <xdebug_globals+1072>, add_local_vars=add_local_vars@entry=true,
    params_as_values=params_as_values@entry=true) at /home/dev/xdebug/src/develop/stack.c:495
#3  0x00007f82fe070ea8 in xdebug_develop_throw_exception_hook (exception=exception@entry=0x7f82d2f52320, file=file@entry=0x7f82d2f52378, line=line@entry=0x7f82d2f52388,
    code=code@entry=0x7f82d2f52368, code_str=code_str@entry=0x0, message=message@entry=0x7f82d2f52348) at /home/dev/xdebug/src/develop/stack.c:1252
#4  0x00007f82fe047a6f in xdebug_throw_exception_hook (exception=0x7f82d2f52320) at /home/dev/xdebug/src/base/base.c:1580
#5  0x0000555c5d0f8c25 in zend_throw_exception_internal ()
#6  0x0000555c5d3a319f in ?? ()
#7  0x0000555c5d3ddafc in execute_ex ()
#8  0x00007f82fe048d65 in xdebug_execute_ex (execute_data=0x7f82fe61a470) at /home/dev/xdebug/src/base/base.c:883
#9  0x0000555c5d3e5e7e in execute_ex ()
#10 0x00007f82fe048d65 in xdebug_execute_ex (execute_data=0x7f82fe61a300) at /home/dev/xdebug/src/base/base.c:883
#11 0x0000555c5d3e5e7e in execute_ex ()
#12 0x00007f82fe048d65 in xdebug_execute_ex (execute_data=0x7f82fe61a150) at /home/dev/xdebug/src/base/base.c:883
#13 0x0000555c5d35ddca in zend_call_function ()
#14 0x0000555c5d35e2a5 in _call_user_function_impl ()
#15 0x0000555c5d3f70b3 in ?? ()
#16 0x00007f82fe0497ad in xdebug_execute_internal (current_execute_data=0x7f82fe61a0b0, return_value=0x7f82fe61a060) at /home/dev/xdebug/src/base/base.c:1018
#17 0x0000555c5d3e5b6c in execute_ex ()
#18 0x00007f82fe048d65 in xdebug_execute_ex (execute_data=0x7f82fe619f80) at /home/dev/xdebug/src/base/base.c:883
#19 0x0000555c5d3e5e7e in execute_ex ()
#20 0x00007f82fe048d65 in xdebug_execute_ex (execute_data=0x7f82fe619e10) at /home/dev/xdebug/src/base/base.c:883
#21 0x0000555c5d3e5e7e in execute_ex ()
#22 0x00007f82fe048d65 in xdebug_execute_ex (execute_data=0x7f82fe619730) at /home/dev/xdebug/src/base/base.c:883
#23 0x0000555c5d3e5e7e in execute_ex ()
```

What I've noticed when we throw an exception error during the test run and it's an unhandled exception, it will result in this segmentation fault.

The following snippet shows us where the segmentation fault is coming from:
image 

### Detials

```
PHP 8.0.30 (cli) (built: Apr 12 2024 11:10:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.30, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.30, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
```

```
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
exif
FFI
fileinfo
filter
ftp
gd
gettext
grpc
hash
iconv
igbinary
imagick
imap
intl
json
libxml
maxminddb
mbstring
mcrypt
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

Best regards,
Gergo

**Pull request closed without merging**
