### PR TITLE
Add Env var for "mode"

### PR DESCRIPTION
**Pull request by exussum12**
Add the new flag mode to what can be picked up though enviroment variables

### CODE REVIEW

**Comment by exussum12** [comment]
Fixes https://bugs.xdebug.org/view.php?id=1824

**Comment by derickr** [comment]
I've just update https://bugs.xdebug.org/1824 to reflect my plans for mode configurability:

At the moment there is only a subset of configuration settings that can be configured through `XDEBUG_CONFIG,` and I am in the process to reduce these with the goal to reduce configuration complexity.

I do want the mode to be configured by an environment variable, but instead I want to use `XDEBUG_MODE`. I need to work out how this interact with the INI settings, as I need to make sure that the right configuration group (env var, or INI settings) take precedence, and I will also need to add tests for this.

I will therefore be closing this PR, but thanks for having a look and creating a ticket so that I don't forget :-).

**Comment by exussum12** [comment]
Ok cool. I assume with the new mode variable a fpm / container restart is needed to switch the mode ? Eg can't go from debugging to profiling without restarting the server ?

**Comment by derickr** [comment]
That's correct, yes. You can however have both on at the same time, but I would discourage that.

**Pull request closed without merging**
