### PR TITLE
Fixed issue #1303: POLLRDHUP is not supported outside of Gnu/Linux

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by Jan-E** [comment]
@derickr Could you merge this one? When checking out from git-head, this causes a Windows build to fail as well.

**Comment by derickr** [comment]
I haven't done so yet because Travis is unhappy: https://travis-ci.org/xdebug/xdebug/builds/132313329

**Comment by Jan-E** [comment]
Right. Now I know why you wanted to load zend_extensions in *.phpt files.

**Comment by derickr** [comment]
TBH, I'm more concerned about this segfault: https://travis-ci.org/xdebug/xdebug/jobs/132313334#L754

Maybe I should keep "nightly" as "allowed to fail" for now.

**Comment by vanhanit** [comment]
Is it failing because of this small change or because of an instable nightly build? Saw that one test also failed for PHP7, but maybe not related to this change?

**Comment by derickr** [comment]
Merged.

**Pull request closed without merging**
