### PR TITLE
Llist to vector

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by mvorisek** [comment]
@derickr I was going to test this and this PR/merge introduced some fatal error.

Steps to reproduce:
- clone https://github.com/atk4/ui
- create demo DB using `php demos/_demo-data/create-sqlite-db.php`
- run phpunit with xdebug (with `master`)

Please confirm, you was able to reproduce. I can produce it consistently.

with this PR/merge:
image

with checked commit before this:
image

this is also answer to your question how I tested the times before - using exactly this repo/steps

**Comment by derickr** [comment]
I'm getting the following error when I try your reproduce case:

> ui$ php -d xdebug.start_with_request=always -d xdebug.mode=profile -d xdebug.profiler_output_name=callgrind.bin -d 
>
> xdebug.output_dir=/tmp ~/phpunit-8.0.4.phar 
> PHPUnit 8.0.4 by Sebastian Bergmann and contributors.
> 
> Cannot open file "/tmp/ui/vendor/autoload.php".

 I had to run `$ php -n -dmemory_limit=8G ~/composer.phar install` which took a loooong time.

**Comment by mvorisek** [comment]
I was able to fresh install with the following steps:
1. `git clone https://github.com/atk4/ui.git` 
2. `cd ui`
3. `composer install` (yes, it takes minute or two to resolve deps - if you can not finish install, use my composer.lock file snapshot - https://pastebin.com/raw/Btm3r4Ef )
4. run `php demos/_demo-data/create-sqlite-db.php` (to create sqlite demo db file)
5. run `php vendor/phpunit/phpunit/phpunit -v  --no-coverage` (you need probably to use the installed phpunit)
6. run with xdebug and profiling enabled

**Comment by derickr** [comment]
I could reproduce it, and also have a partial fix... hunting down a memory issue.

**Pull request closed without merging**
