### PR TITLE
Wrapper elements on strings to allow for styling

### PR DESCRIPTION
**Pull request by Brugman**
The chosen class names should accurately represent the data, if I used the wrong terminology please correct. I've appended them to the table class so they are not generic enough for a user to accidentally style.

### CODE REVIEW

**Comment by derickr** [comment]
Thanks for the patch!

Unfortunately (sorry), this breaks quite a few test cases - basically all tests where it tests for the output of a stack dump :-) Have a look at what Travis says: https://travis-ci.org/xdebug/xdebug/jobs/78491577

It'd be great if you could fix these test cases as well. You can run test cases in the Xdebug source repository with "make test" to see your results.

**Comment by derickr** [comment]
Did you have some time to look at the test failures? Without these gone, I can't really merge this. Please have a look, and once it's done, and Xdebug for PHP 7 is out, I'll merge it.

**Comment by derickr** [comment]
Most of the PHP 7 stuff is in now, so I'd be looking at adding features now. Did you have a look at the test failures?

**Comment by Brugman** [comment]
Thanks for your time. This was just a shot in the dark. I'm not familiar with testing and Travis at this time so I'm letting it be.

**Pull request closed without merging**
