### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by websoftwares**
Changed to 2.6 version in README.rst

### CODE REVIEW

**Comment by derickr** [comment]
Hi!

This should go to the xdebug_2_5 branch as master is for 2.6 releases (for which the README also need to be updated for.

cheers,
Derick
-- 
http://derickrethans.nl | http://xdebug.org
twitter: @derickr and @xdebug

**Comment by websoftwares** [comment]
Hello updated this to make it 2.6 and then il create a new PR on the xdebug_2_5 branch.

**Comment by kenorb** [comment]
Related: #343

**Comment by derickr** [comment]
I have just merged this (after rebase) - thanks for the PR!

**Pull request closed without merging**
