### PR TITLE
At error_cb, set status header before send header

### PR DESCRIPTION
**Pull request by RobberPhex**
Fix <https://bugs.xdebug.org/view.php?id=1552>

### CODE REVIEW

**Comment by derickr** [comment]
Hi!

I haven't managed to look at the code yet, but can you please target this to the xdebug_2_6 branch as explained in the Contributing Guidelines on the website? I would also very much like a test case.

cheers,
Derick

**Comment by RobberPhex** [comment]
@derickr 
Considering that `Xdebug 2.7.2` was released, should I set the target branch to `xdebug_2_7`?

**Comment by derickr** [comment]
Yes, it should be set to `xdebug_2_7`, but the main reason that I didn't look into/merge this yet, is that I think that the changes between PHP's vanilla `php_error_cb`, and the Xdebug one need a better sync first. These changes look correct, but are quite different from what PHP now does normally.

**Comment by derickr** [comment]
I'm closing this PR, as the underlying ticket has been closed as "Works as expected". The behaviour in PHP without Xdebug loaded is the same.

**Pull request closed without merging**
